export const COOKIES_AUTHORIZATION_TOKEN = 'Authorization';

// SET

export const SET_LOGOUT_USER = 'SET_LOGOUT_USER';
export const SET_DATA_USERS_LIST = 'SET_DATA_USERS_LIST';
export const SET_DATA_SERVICEPROVIDER_LIST = 'SET_DATA_SERVICEPROVIDER_LIST';
export const SET_DATA_ROOMS_LIST = 'SET_DATA_ROOMS_LIST';
export const SET_SERVICE_ID = 'SET_SERVICE_ID';
export const SET_SERVICEPROVIDER_ID = 'SET_SERVICEPROVIDER_ID';
export const SET_MODAL = 'SET_MODAL';
export const SET_DATA_USERS = 'SET_DATA_USERS';
export const SET_DATA_USER = 'SET_DATA_USER';
export const SET_DATA_ROOMS_LIST_BY_ID = 'SET_DATA_ROOMS_LIST_BY_ID';
export const SET_DATA_SERVICE_PROVIDER_LIST_BY_ID = 'SET_DATA_SERVICE_PROVIDER_LIST_BY_ID';
export const SET_DATA_TAGS_LIST = 'SET_DATA_TAGS_LIST';
export const SET_DATA_TAG_LIST_BY_ID = 'SET_DATA_TAG_LIST_BY_ID';
export const SET_DATA_USER_LIST_BY_ID = 'SET_DATA_USER_LIST_BY_ID';
export const SET_DATA_ROOM_LIST = 'SET_DATA_ROOM_LIST';
export const SET_DATA_EQUIPMENTS_LIST = 'SET_DATA_EQUIPMENTS_LIST';
export const SET_DATA_ROOMS_LIST_SERVICE_PROVIDER = 'SET_DATA_ROOMS_LIST_SERVICE_PROVIDER';
export const SET_DATA_TAGS_CAT = 'SET_DATA_TAGS_CAT';
export const SET_DATA_DASHBOARD = 'SET_DATA_DASHBOARD';
export const SET_DATA_BOOKING_LIST = 'SET_DATA_BOOKING_LIST';
export const SET_DATA_BOOKING_STATUT = 'SET_DATA_BOOKING_STATUT';

// ADD

export const ADD_SERVICE_PROVIDER_SUCCESS = 'ADD_SERVICE_PROVIDER_SUCCESS';
export const ADD_SERVICE_PROVIDER_ERROR = 'ADD_SERVICE_PROVIDER_ERROR';
export const ADD_USER_SUCCESS = 'ADD_USER_SUCCESS';
export const ADD_USER_ERROR = 'ADD_USER_ERROR';
export const ADD_ROOM_SUCCESS = 'ADD_ROOM_SUCCESS';
export const ADD_ROOM_ERROR = 'ADD_ROOM_ERROR';
export const ADD_TAG_SUCCESS = 'ADD_TAG_SUCCESS';
export const ADD_TAG_ERROR = 'ADD_TAG_ERROR';

// UPDATE

export const UPDATE_SERVICE_PROVIDER_SUCCESS = 'UPDATE_SERVICE_PROVIDER_SUCCESS';
export const UPDATE_SERVICE_PROVIDER_ERROR = 'UPDATE_SERVICE_PROVIDER_ERROR';
export const UPDATE_USER_SUCCESS = 'UPDATE_USER_SUCCESS';
export const UPDATE_USER_ERROR = 'UPDATE_USER_ERROR';
export const UPDATE_ROOM_ERROR = 'UPDATE_ROOM_ERROR';
export const UPDATE_ROOM_SUCCESS = 'UPDATE_ROOM_SUCCESS';
export const UPDATE_TAG_SUCCESS = 'UPDATE_TAG_SUCCESS';
export const UPDATE_TAG_ERROR = 'UPDATE_TAG_ERROR';
export const UPDATE_PROFIL_SUCCESS = 'UPDATE_PROFIL_SUCCESS';
export const UPDATE_DATA_CAROUSEL = 'UPDATE_DATA_CAROUSEL';
export const UPDATE_IMAGES_TO_UPLOAD = 'UPDATE_IMAGES_TO_UPLOAD';
export const UPDATE_BOOKING_SUCCESS = 'UPDATE_BOOKING_SUCCESS';
export const UPDATE_BOOKING_ERROR = 'UPDATE_BOOKING_ERROR';


// DELETE

export const DELETE_ROOM_SUCCESS = 'DELETE_ROOM_SUCCESS';
export const DELETE_ROOM_ERROR = 'DELETE_ROOM_ERROR';
export const DELETE_USER_SUCCESS = 'DELETE_USER_SUCCESS';
export const DELETE_USER_ERROR = 'DELETE_USER_ERROR';
export const DELETE_SERVICE_PROVIDER_SUCCESS = 'DELETE_SERVICE_PROVIDER_SUCCESS';
export const DELETE_SERVICE_PROVIDER_ERROR = 'DELETE_SERVICE_PROVIDER_ERROR';
export const DELETE_TAG_SUCCESS = 'DELETE_TAG_SUCCESS';
export const DELETE_TAG_ERROR = 'DELETE_TAG_ERROR';


// IS EDIT

export const IS_EDIT_ROOM = 'IS_EDIT_ROOM';
export const IS_EDIT_SERVICE_PROVIDER = 'IS_EDIT_SERVICE_PROVIDER';
export const IS_EDIT_TAG = 'IS_EDIT_TAG';
export const IS_EDIT_PROFIL = 'IS_EDIT_PROFIL';
export const IS_EDIT_USER = 'IS_EDIT_USER';


// ERROR

export const LOGIN_ERROR = 'LOGIN_ERROR';
